### ISSUE TITLE
Description of the package in Pypi

### ISSUE THREAD

**Issue by gfl-math-stat-info** [gfl-math-stat-info/ggames#4]
**Describe the bug**
The README file is not shown as a description of the package in Pypi.

**To Reproduce**
Take a look to https://pypi.org/project/ggames/#description.

**Expected behavior**
The README file supposed to be shown as a description of this package.

**Comment by priteshkulshreshtha** [comment]
created a pull request (PR#5) for this

**Comment by gfl-math-stat-info** [comment]
It's all good. Thank to @priteshkulshreshtha.
